In [49]:
import numpy as np
import time

In [50]:
# data creation in NumPy often has a first parameter which is the shape of an object which can be a single value or a tuple
# the shape of a numpy array is a tuple with values for each dimension
# in a 1d array, the output is (# of elements,)
# in a 2d array, the output is (# of rowns, #number of colums)
a = np.zeros(4);                
print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             
print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4);
print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.04997798 0.77390955 0.93782363 0.5792328 ], a shape = (4,), a data type = float64


In [51]:
# some methods fill arrays with a value bu don't take shape as a parameter
a = np.arange(4.);              
print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.53516563 0.80204309 0.24814448 0.59096694], a shape = (4,), a data type = float64


In [52]:
# you can also create an array by manually assigning values
a = np.array([5,4,3,2]); 
print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); 
print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int32
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


In [53]:
# you can access an element using the index
# to access the last element you ue a negative index, negative indexes count from the last element
# indexes must be within the range of the vector or they will error out, the range is the length of the vector - 1 because the index starts at 0
a = np.arange(10)
print(a)
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")
print(f"a[-1] = {a[-1]}")
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


In [54]:
# vector slicing operations(extracting certain indexes)
a = np.arange(10)
print(f"a = {a}")
c = a[2:7:1]; # access 5 consecutive elements(start:stop:step)    
print("a[2:7:1] = ", c)
c = a[2:7:2]; # access 3 elements separated by two(start:stop:step)
print("a[2:7:2] = ", c)
c = a[3:]; # access all elements index 3 and above   
print("a[3:] = ", c)
c = a[:3]; # access all elements below index 3
print("a[:3] = ", c)
c = a[:]; # access all elements
print("a[:] = ", c)

a = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:] =  [3 4 5 6 7 8 9]
a[:3] =  [0 1 2]
a[:] =  [0 1 2 3 4 5 6 7 8 9]


In [55]:
# you can perform many operations of every element in an array
a = np.array([1,2,3,4])
print(f"a: {a}") # negate elements of a
b = -a 
print(f"b = -a: {b}") # sum of all elements of a
b = np.sum(a) 
print(f"b = np.sum(a): {b}")
b = np.mean(a) # average of all elements of a
print(f"b = np.mean(a): {b}")
b = a**2 # square of all elements of a
print(f"b = a**2: {b}")

a: [1 2 3 4]
b = -a: [-1 -2 -3 -4]
b = np.sum(a): 10
b = np.mean(a): 2.5
b = a**2: [ 1  4  9 16]


In [56]:
# we can add all corresponding elements in lists a[i] + b[i] by using a + b
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


In [57]:
# in order to perform operations on entire vectots, they must be the same length
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


In [58]:
# multiply all elements in array a by a scalar
a = np.array([1, 2, 3, 4])
b = 5 * a 
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


In [59]:
# assuuming a and b are the same length, we can make our own dot function
# the dot function multiplies a and b and adds x for every index
def my_dot(a, b): 
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [60]:
# testing using 1d array
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


In [61]:
# we can use the NumPy built in dot function which is more efficient with processing, speed, and is easier to read
# note that both implementations complete the same task and return the same things including data types
# also note that the product of the dot function has no shape
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"NumPy 1d np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1d np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")

NumPy 1d np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1d np.dot(b, a) = 24, np.dot(a, b).shape = () 


In [62]:
# using the dot function is more efficient as seen in the times below, although the difference is small now, in very large data sets, this can make a significant differenve
np.random.seed(1)
a = np.random.rand(10000000) # very large arrays
b = np.random.rand(10000000) # very large arrays
start = time.time() # capture start time
c = np.dot(a, b)
end = time.time() # capture end time
print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(start-end):.4f} ms ")
start = time.time() # capture start time
c = my_dot(a,b)
end = time.time() # capture end time
print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(start-end):.4f} ms ")
del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: -13.9313 ms 
my_dot(a, b) =  2501072.5817
loop version duration: -2835.9728 ms 


In [63]:
# showing common examples in course 1
x = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"x[1] has shape {x[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


In [64]:
# a matrix is a 2d or nd array which is essentially an array of arrays or arrays containing arrays at a certain index
a = np.zeros((1, 5)) # 1 row and 5 columns                                     
print(f"a shape = {a.shape}, a = {a}")                     
a = np.zeros((2, 1)) # 2 rows and 1 column                                                             
print(f"a shape = {a.shape}, a = {a}") 
a = np.random.random_sample((1, 1)) # 1 row and 1 column
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.44236513]]


In [65]:
# certain NumPy methods use memory and fills it with user specified values
a = np.array([[5], [4], [3]]);   
print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],  # you can also
              [4],  # separate values
              [3]]); # into separate rows for easier visualization
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


In [66]:
# NumPy also offers vector indexing operations on matrices
# reshape is a easy way to create matrices, first parameter is # of rows and the second is # of columns
# if the first parameter is -1, it tells the function to calculate the number of rows based on the array size and # of columnns given
a = np.arange(6).reshape(-1, 2)
print(f"a.shape: {a.shape}, \na = {a}")
# to access one element in a row
print(f"\na[2,0].shape: {a[2, 0].shape}, a[2,0] = {a[2, 0]}, type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")
# to access an entire row
print(f"a[2].shape: {a[2].shape}, a[2] = {a[2]}, type(a[2]) = {type(a[2])}")

a.shape: (3, 2), 
a = [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape: (), a[2,0] = 4, type(a[2,0]) = <class 'numpy.int32'> Accessing an element returns a scalar

a[2].shape: (2,), a[2] = [4 5], type(a[2]) = <class 'numpy.ndarray'>


In [70]:
# vector 2d slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")
print("\na[0, 2:7:1] = ", a[0, 2:7:1],", a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1d array") # access 5 consecutive elements (start:stop:step)
print("\na[:, 2:7:1] = \n", a[:, 2:7:1],", a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2d array") # access 5 consecutive elements (start:stop:step) in two rows
print("\na[:,:] = \n", a[:,:],", a[:,:].shape =", a[:,:].shape) # access all elements
print("\na[1,:] = ", a[1,:],", a[1,:].shape =", a[1,:].shape, "a 1d array") # access all elements in one row, very commonly used
print("\na[1] = ", a[1],", a[1].shape =", a[1].shape, "a 1d array")# same as above, replace 1 with 2 for second row

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

a[0, 2:7:1] =  [2 3 4 5 6] , a[0, 2:7:1].shape = (5,) a 1d array

a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] , a[:, 2:7:1].shape = (2, 5) a 2d array

a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] , a[:,:].shape = (2, 10)

a[1,:] =  [10 11 12 13 14 15 16 17 18 19] , a[1,:].shape = (10,) a 1d array

a[1] =  [10 11 12 13 14 15 16 17 18 19] , a[1].shape = (10,) a 1d array
